namespace IceCoffee.Db4Net.Core.OptionalAttributes
{
    /// <summary>
    /// Indicates that a property is generated by the database.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class DatabaseGeneratedAttribute : Attribute
    {
    }
}